FROM node:22.6.0-alpine AS base

WORKDIR /app

# Install dependencies
RUN npm install better-sqlite3@11.3.0 drizzle-orm@0.33.0 drizzle-kit@0.22.8 zod@3.23.8

# Copy package.json (just for scripts)
COPY package.json ./

# Copy scripts
COPY ./db ./db

# Copy Drizzle config
COPY drizzle.config.ts ./